version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: residence_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: residence_db
      MYSQL_USER: residence_user
      MYSQL_PASSWORD: residence_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: