spring.application.name=residence

# ===============================
# SERVER
# ===============================
server.port=8080

# ===============================
# DATASOURCE (MySQL Docker)
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/residence_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=residence_user
spring.datasource.password=residence_pass
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Hibernate 7 compatible dialect pour MySQL 8
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
